
import { getDb } from "./db";
import { products } from "../drizzle/schema";
import * as dotenv from "dotenv";

dotenv.config();


const miners = [
    // Bitmain Antminer
    {
        name: "Antminer S21 Pro",
        slug: "antminer-s21-pro",
        manufacturer: "Bitmain",
        model: "S21 Pro",
        algorithm: "SHA-256",
        hashrate: "234 TH/s",
        power: 3510,
        efficiency: "15.0 J/TH",
        price: 450000, // $4500.00
        currency: "USD",
        condition: "new",
        cooling: "air",
        category: "bitcoin-miner",
        coin: "BTC",
        imageUrl: "https://placehold.co/600x400?text=Antminer+S21+Pro",
        description: "The latest generation Bitcoin miner from Bitmain with superior efficiency.",
        inStock: true,
        featured: true,
    },
    {
        name: "Antminer S21 XP Hydro",
        slug: "antminer-s21-xp-hydro",
        manufacturer: "Bitmain",
        model: "S21 XP Hydro",
        algorithm: "SHA-256",
        hashrate: "473 TH/s",
        power: 5676,
        efficiency: "12.0 J/TH",
        price: 850000,
        currency: "USD",
        condition: "new",
        cooling: "hydro",
        category: "bitcoin-miner",
        coin: "BTC",
        imageUrl: "https://placehold.co/600x400?text=Antminer+S21+XP+Hydro",
        description: "High-performance hydro-cooling miner for industrial scale operations.",
        inStock: true,
        featured: true,
    },
    {
        name: "Antminer L7",
        slug: "antminer-l7",
        manufacturer: "Bitmain",
        model: "L7",
        algorithm: "Scrypt",
        hashrate: "9500 MH/s",
        power: 3425,
        efficiency: "0.36 J/MH",
        price: 680000,
        currency: "USD",
        condition: "new",
        cooling: "air",
        category: "altcoin-miner",
        coin: "LTC/DOGE",
        imageUrl: "https://placehold.co/600x400?text=Antminer+L7",
        description: "Top-tier Scrypt miner for Litecoin and Dogecoin mining.",
        inStock: true,
        featured: true,
    },
    {
        name: "Antminer KS5 Pro",
        slug: "antminer-ks5-pro",
        manufacturer: "Bitmain",
        model: "KS5 Pro",
        algorithm: "kHeavyHash",
        hashrate: "21 TH/s",
        power: 3150,
        efficiency: "150 J/TH",
        price: 1200000,
        currency: "USD",
        condition: "new",
        cooling: "air",
        category: "altcoin-miner",
        coin: "KAS",
        imageUrl: "https://placehold.co/600x400?text=Antminer+KS5+Pro",
        description: "Powerful Kaspa miner for high profitability.",
        inStock: true,
        featured: true,
    },

    // MicroBT Whatsminer
    {
        name: "Whatsminer M60S",
        slug: "whatsminer-m60s",
        manufacturer: "MicroBT",
        model: "M60S",
        algorithm: "SHA-256",
        hashrate: "186 TH/s",
        power: 3441,
        efficiency: "18.5 J/TH",
        price: 320000,
        currency: "USD",
        condition: "new",
        cooling: "air",
        category: "bitcoin-miner",
        coin: "BTC",
        imageUrl: "https://placehold.co/600x400?text=Whatsminer+M60S",
        description: "Reliable and efficient air-cooled Bitcoin miner from MicroBT.",
        inStock: true,
    },
    {
        name: "Whatsminer M66S",
        slug: "whatsminer-m66s",
        manufacturer: "MicroBT",
        model: "M66S",
        algorithm: "SHA-256",
        hashrate: "298 TH/s",
        power: 5513,
        efficiency: "18.5 J/TH",
        price: 550000,
        currency: "USD",
        condition: "new",
        cooling: "immersion",
        category: "Bitcoin Miner",
        coin: "BTC",
        imageUrl: "https://placehold.co/600x400?text=Whatsminer+M66S",
        description: "Immersion cooling ready miner for maximum density and efficiency.",
        inStock: true,
    },

    // Canaan Avalon
    {
        name: "Avalon A1566",
        slug: "avalon-a1566",
        manufacturer: "Canaan",
        model: "A1566",
        algorithm: "SHA-256",
        hashrate: "185 TH/s",
        power: 3420,
        efficiency: "18.5 J/TH",
        price: 290000,
        currency: "USD",
        condition: "new",
        cooling: "air",
        category: "Bitcoin Miner",
        coin: "BTC",
        imageUrl: "https://placehold.co/600x400?text=Avalon+A1566",
        description: "Cost-effective Bitcoin miner with solid performance.",
        inStock: true,
    },

    // Goldshell
    {
        name: "Goldshell KA Box Pro",
        slug: "goldshell-ka-box-pro",
        manufacturer: "Goldshell",
        model: "KA Box Pro",
        algorithm: "kHeavyHash",
        hashrate: "1.6 TH/s",
        power: 600,
        efficiency: "375 J/TH",
        price: 85000,
        currency: "USD",
        condition: "new",
        cooling: "air",
        category: "Home Miner",
        coin: "KAS",
        imageUrl: "https://placehold.co/600x400?text=Goldshell+KA+Box+Pro",
        description: "Quiet and efficient home miner for Kaspa.",
        inStock: true,
    },
    {
        name: "Goldshell Mini Doge 3",
        slug: "goldshell-mini-doge-3",
        manufacturer: "Goldshell",
        model: "Mini Doge 3",
        algorithm: "Scrypt",
        hashrate: "650 MH/s",
        power: 400,
        efficiency: "0.61 J/MH",
        price: 45000,
        currency: "USD",
        condition: "new",
        cooling: "air",
        category: "Home Miner",
        coin: "LTC/DOGE",
        imageUrl: "https://placehold.co/600x400?text=Goldshell+Mini+Doge+3",
        description: "Perfect entry-level home miner for Dogecoin and Litecoin.",
        inStock: true,
    },

    // IceRiver
    {
        name: "IceRiver KS3M",
        slug: "iceriver-ks3m",
        manufacturer: "IceRiver",
        model: "KS3M",
        algorithm: "kHeavyHash",
        hashrate: "6 TH/s",
        power: 3400,
        efficiency: "566 J/TH",
        price: 420000,
        currency: "USD",
        condition: "new",
        cooling: "air",
        category: "Altcoin Miner",
        coin: "KAS",
        imageUrl: "https://placehold.co/600x400?text=IceRiver+KS3M",
        description: "High hashrate Kaspa miner for serious mining operations.",
        inStock: true,
    },
    {
        name: "IceRiver AL0",
        slug: "iceriver-al0",
        manufacturer: "IceRiver",
        model: "AL0",
        algorithm: "Blake3",
        hashrate: "400 GH/s",
        power: 100,
        efficiency: "0.25 J/GH",
        price: 65000,
        currency: "USD",
        condition: "new",
        cooling: "air",
        category: "Home Miner",
        coin: "ALPH",
        imageUrl: "https://placehold.co/600x400?text=IceRiver+AL0",
        description: "Efficient home miner for Alephium.",
        inStock: true,
    },

    // IPollo
    {
        name: "iPollo V1 Mini",
        slug: "ipollo-v1-mini",
        manufacturer: "iPollo",
        model: "V1 Mini",
        algorithm: "Ethash",
        hashrate: "300 MH/s",
        power: 240,
        efficiency: "0.8 J/MH",
        price: 55000,
        currency: "USD",
        condition: "new",
        cooling: "air",
        category: "Home Miner",
        coin: "ETC/ZIL",
        imageUrl: "https://placehold.co/600x400?text=iPollo+V1+Mini",
        description: "Compact miner for Ethereum Classic and Zilliqa.",
        inStock: true,
    },

    // Innosilicon
    {
        name: "Innosilicon A11 Pro",
        slug: "innosilicon-a11-pro",
        manufacturer: "Innosilicon",
        model: "A11 Pro",
        algorithm: "Ethash",
        hashrate: "1500 MH/s",
        power: 2350,
        efficiency: "1.56 J/MH",
        price: 950000,
        currency: "USD",
        condition: "new",
        cooling: "air",
        category: "Altcoin Miner",
        coin: "ETC",
        imageUrl: "https://placehold.co/600x400?text=Innosilicon+A11+Pro",
        description: "Powerful Ethash miner for ETC mining.",
        inStock: true,
    },

    // VolcMiner
    {
        name: "VolcMiner D1",
        slug: "volcminer-d1",
        manufacturer: "VolcMiner",
        model: "D1",
        algorithm: "Scrypt",
        hashrate: "17 GH/s",
        power: 3800,
        efficiency: "0.22 J/MH",
        price: 1100000,
        currency: "USD",
        condition: "new",
        cooling: "air",
        category: "Altcoin Miner",
        coin: "LTC/DOGE",
        imageUrl: "https://placehold.co/600x400?text=VolcMiner+D1",
        description: "New high-performance Scrypt miner.",
        inStock: true,
    },

    // Bitdeer
    {
        name: "Sealminer A1",
        slug: "sealminer-a1",
        manufacturer: "Bitdeer",
        model: "A1",
        algorithm: "SHA-256",
        hashrate: "100 TH/s",
        power: 2500,
        efficiency: "25.0 J/TH",
        price: 150000,
        currency: "USD",
        condition: "new",
        cooling: "air",
        category: "Bitcoin Miner",
        coin: "BTC",
        imageUrl: "https://placehold.co/600x400?text=Sealminer+A1",
        description: "Bitdeer's entry into the hardware market.",
        inStock: true,
    },

    // ===== NEW ADDITIONS FROM CATALOG 2024-2025 =====

    // Bitmain Antminer
    {
        name: "Bitmain Antminer S23 Hydro",
        slug: "antminer-s23-hydro",
        manufacturer: "Bitmain",
        model: "S23 Hydro",
        algorithm: "SHA-256",
        hashrate: "580 TH/s",
        power: 5510,
        efficiency: "9.5 J/TH",
        price: 1740000,
        currency: "USD",
        condition: "new",
        cooling: "hydro",
        category: "Bitcoin Miner",
        coin: "BTC",
        imageUrl: "https://placehold.co/600x400?text=Antminer+S23+Hydro",
        description: "Enterprise-scale immersion hydro-cooling miner with industry-leading efficiency.",
        inStock: true,
    },
    {
        name: "Bitmain Antminer U3S23H",
        slug: "antminer-u3s23h",
        manufacturer: "Bitmain",
        model: "U3S23H",
        algorithm: "SHA-256",
        hashrate: "1160 TH/s",
        power: 11020,
        efficiency: "9.5 J/TH",
        price: 3480000,
        currency: "USD",
        condition: "new",
        cooling: "hydro",
        category: "Bitcoin Miner",
        coin: "BTC",
        imageUrl: "https://placehold.co/600x400?text=Antminer+U3S23H",
        description: "Maximum performance hydro-cooling miner for large-scale operations.",
        inStock: true,
    },
    {
        name: "Bitmain Antminer S21+",
        slug: "antminer-s21-plus",
        manufacturer: "Bitmain",
        model: "S21+",
        algorithm: "SHA-256",
        hashrate: "216 TH/s",
        power: 3564,
        efficiency: "16.5 J/TH",
        price: 324000,
        currency: "USD",
        condition: "new",
        cooling: "air",
        category: "Bitcoin Miner",
        coin: "BTC",
        imageUrl: "https://placehold.co/600x400?text=Antminer+S21+",
        description: "Latest generation air-cooled miner with improved efficiency.",
        inStock: true,
    },
    {
        name: "Bitmain Antminer S19 Pro+ Hydro",
        slug: "antminer-s19-pro-plus-hydro",
        manufacturer: "Bitmain",
        model: "S19 Pro+ Hydro",
        algorithm: "SHA-256",
        hashrate: "191 TH/s",
        power: 5252,
        efficiency: "27.5 J/TH",
        price: 229200,
        currency: "USD",
        condition: "new",
        cooling: "hydro",
        category: "Bitcoin Miner",
        coin: "BTC",
        imageUrl: "https://placehold.co/600x400?text=Antminer+S19+Pro++Hydro",
        description: "Cost-effective hydro-cooling solution for professional mining.",
        inStock: true,
    },
    {
        name: "Bitmain Antminer D7",
        slug: "antminer-d7",
        manufacturer: "Bitmain",
        model: "D7",
        algorithm: "Blake2b",
        hashrate: "1.24 TH/s",
        power: 3148,
        efficiency: "2.54 J/GH",
        price: 450000,
        currency: "USD",
        condition: "new",
        cooling: "air",
        category: "Altcoin Miner",
        coin: "DCR",
        imageUrl: "https://placehold.co/600x400?text=Antminer+D7",
        description: "Powerful Decred miner for merged mining operations.",
        inStock: true,
    },

    // Canaan Avalon
    {
        name: "Canaan Avalon A1566I",
        slug: "avalon-a1566i",
        manufacturer: "Canaan",
        model: "A1566I",
        algorithm: "SHA-256",
        hashrate: "249 TH/s",
        power: 3400,
        efficiency: "13.6 J/TH",
        price: 487900,
        currency: "USD",
        condition: "new",
        cooling: "air",
        category: "Bitcoin Miner",
        coin: "BTC",
        imageUrl: "https://placehold.co/600x400?text=Avalon+A1566I",
        description: "High-performance Bitcoin miner from Canaan's latest A15 series.",
        inStock: true,
    },
    {
        name: "Canaan Avalon A1466I",
        slug: "avalon-a1466i",
        manufacturer: "Canaan",
        model: "A1466I",
        algorithm: "SHA-256",
        hashrate: "170 TH/s",
        power: 3315,
        efficiency: "19.5 J/TH",
        price: 380000,
        currency: "USD",
        condition: "new",
        cooling: "air",
        category: "Bitcoin Miner",
        coin: "BTC",
        imageUrl: "https://placehold.co/600x400?text=Avalon+A1466I",
        description: "Improved version of the A1466 with enhanced stability.",
        inStock: true,
    },
    {
        name: "Canaan Avalon A1346",
        slug: "avalon-a1346",
        manufacturer: "Canaan",
        model: "A1346",
        algorithm: "SHA-256",
        hashrate: "110 TH/s",
        power: 3200,
        efficiency: "29.1 J/TH",
        price: 184900,
        currency: "USD",
        condition: "new",
        cooling: "air",
        category: "Bitcoin Miner",
        coin: "BTC",
        imageUrl: "https://placehold.co/600x400?text=Avalon+A1346",
        description: "Entry-level to mid-range mining solution.",
        inStock: true,
    },
    {
        name: "Canaan Avalon Nano 3S",
        slug: "avalon-nano-3s",
        manufacturer: "Canaan",
        model: "Nano 3S",
        algorithm: "SHA-256",
        hashrate: "6 TH/s",
        power: 200,
        efficiency: "33.3 J/TH",
        price: 39900,
        currency: "USD",
        condition: "new",
        cooling: "air",
        category: "Home Miner",
        coin: "BTC",
        imageUrl: "https://placehold.co/600x400?text=Avalon+Nano+3S",
        description: "Educational and hobby mining device with very low noise.",
        inStock: true,
    },

    // MicroBT Whatsminer
    {
        name: "MicroBT Whatsminer M63S+",
        slug: "whatsminer-m63s-plus",
        manufacturer: "MicroBT",
        model: "M63S+",
        algorithm: "SHA-256",
        hashrate: "150 TH/s",
        power: 3450,
        efficiency: "23 J/TH",
        price: 420000,
        currency: "USD",
        condition: "new",
        cooling: "air",
        category: "Bitcoin Miner",
        coin: "BTC",
        imageUrl: "https://placehold.co/600x400?text=Whatsminer+M63S+",
        description: "Mid-to-high performance Bitcoin mining with 5nm technology.",
        inStock: true,
    },
    {
        name: "MicroBT Whatsminer M65S",
        slug: "whatsminer-m65s",
        manufacturer: "MicroBT",
        model: "M65S",
        algorithm: "SHA-256",
        hashrate: "150 TH/s",
        power: 3500,
        efficiency: "23.3 J/TH",
        price: 450000,
        currency: "USD",
        condition: "new",
        cooling: "air",
        category: "Bitcoin Miner",
        coin: "BTC",
        imageUrl: "https://placehold.co/600x400?text=Whatsminer+M65S",
        description: "Latest generation 5nm chip technology.",
        inStock: true,
    },
    {
        name: "MicroBT Whatsminer M30S+",
        slug: "whatsminer-m30s-plus",
        manufacturer: "MicroBT",
        model: "M30S+",
        algorithm: "SHA-256",
        hashrate: "100 TH/s",
        power: 3400,
        efficiency: "34 J/TH",
        price: 180000,
        currency: "USD",
        condition: "new",
        cooling: "air",
        category: "Bitcoin Miner",
        coin: "BTC",
        imageUrl: "https://placehold.co/600x400?text=Whatsminer+M30S+",
        description: "Cost-conscious mining option.",
        inStock: true,
    },
    {
        name: "MicroBT Whatsminer M31S",
        slug: "whatsminer-m31s",
        manufacturer: "MicroBT",
        model: "M31S",
        algorithm: "SHA-256",
        hashrate: "76 TH/s",
        power: 3192,
        efficiency: "42 J/TH",
        price: 120000,
        currency: "USD",
        condition: "new",
        cooling: "air",
        category: "Bitcoin Miner",
        coin: "BTC",
        imageUrl: "https://placehold.co/600x400?text=Whatsminer+M31S",
        description: "Entry to mid-level mining with built-in PSU.",
        inStock: true,
    },
    {
        name: "MicroBT Whatsminer M32",
        slug: "whatsminer-m32",
        manufacturer: "MicroBT",
        model: "M32",
        algorithm: "SHA-256",
        hashrate: "68 TH/s",
        power: 3432,
        efficiency: "52 J/TH",
        price: 90000,
        currency: "USD",
        condition: "new",
        cooling: "air",
        category: "Bitcoin Miner",
        coin: "BTC",
        imageUrl: "https://placehold.co/600x400?text=Whatsminer+M32",
        description: "Budget mining option.",
        inStock: true,
    },

    // Innosilicon
    {
        name: "Innosilicon A10 Pro+",
        slug: "innosilicon-a10-pro-plus",
        manufacturer: "Innosilicon",
        model: "A10 Pro+",
        algorithm: "Ethash",
        hashrate: "750 MH/s",
        power: 1350,
        efficiency: "1.8 J/MH",
        price: 125000,
        currency: "USD",
        condition: "new",
        cooling: "air",
        category: "Altcoin Miner",
        coin: "ETC",
        imageUrl: "https://placehold.co/600x400?text=Innosilicon+A10+Pro+",
        description: "Popular mid-range ETC mining option with 7GB memory.",
        inStock: true,
    },
    {
        name: "Innosilicon A10 Pro 6GB",
        slug: "innosilicon-a10-pro-6gb",
        manufacturer: "Innosilicon",
        model: "A10 Pro 6GB",
        algorithm: "Ethash",
        hashrate: "500 MH/s",
        power: 750,
        efficiency: "1.5 J/MH",
        price: 99900,
        currency: "USD",
        condition: "new",
        cooling: "air",
        category: "Altcoin Miner",
        coin: "ETC",
        imageUrl: "https://placehold.co/600x400?text=Innosilicon+A10+Pro+6GB",
        description: "Budget-friendly ETC mining.",
        inStock: true,
    },
    {
        name: "Innosilicon A5+",
        slug: "innosilicon-a5-plus",
        manufacturer: "Innosilicon",
        model: "A5+",
        algorithm: "Blake2b",
        hashrate: "600 MH/s",
        power: 1000,
        efficiency: "1.67 J/MH",
        price: 80000,
        currency: "USD",
        condition: "new",
        cooling: "air",
        category: "Altcoin Miner",
        coin: "DCR",
        imageUrl: "https://placehold.co/600x400?text=Innosilicon+A5+",
        description: "Optimized for Decred (DCR) mining.",
        inStock: true,
    },

    // Ebang
    {
        name: "Ebang EBIT E21",
        slug: "ebang-ebit-e21",
        manufacturer: "Ebang",
        model: "EBIT E21",
        algorithm: "SHA-256",
        hashrate: "120 TH/s",
        power: 3400,
        efficiency: "28.3 J/TH",
        price: 450000,
        currency: "USD",
        condition: "new",
        cooling: "air",
        category: "Bitcoin Miner",
        coin: "BTC",
        imageUrl: "https://placehold.co/600x400?text=Ebang+EBIT+E21",
        description: "Mid-range enterprise mining solution.",
        inStock: true,
    }
];

async function seed() {
    console.log("Seeding products...");
    const db = await getDb();
    if (!db) {
        console.error("Failed to connect to database");
        process.exit(1);
    }

    for (const miner of miners) {
        try {
            await db.insert(products).values(miner as any).onConflictDoNothing();
            console.log(`Added ${miner.name}`);
        } catch (error) {
            console.error(`Failed to add ${miner.name}:`, error);
        }
    }

    console.log("Seeding complete!");
    process.exit(0);
}

seed();
